### ISSUE TITLE
【Bug】Some special symbols cannot be processed

### ISSUE THREAD

**Issue by sdwdjzhy** [spectreconsole/wcwidth#8] opened 2024-08-27 03:38 UTC
**Information**
 - OS: Win
 - Version: 0.49.1
 - Terminal: cmd

**Describe the bug**

Some special characters cannot be counted as 2, like ℃、℉

**To Reproduce**
```C#

using Spectre.Console;

var table = new Spectre.Console.Table();
table.AddColumns("Name", "Value", "Description");
table.AddRow("test", "中文", "中文 mix English");
table.AddRow("test", "中文", "使用特殊字符℃");
table.AddRow("test", "中文", "使用特殊字符℉");
table.AddRow("test", "中文", "使用特殊字符");

AnsiConsole.Write(table);

```

**Expected behavior**
Table alignment

**Screenshots**

![微信截图_20240827111457](https://github.com/user-attachments/assets/5b7b14e6-ba34-402b-819c-7dfd6d88ae10)

**Additional context**

---
Please upvote :+1: this issue if you are interested in it.

**Comment by sdwdjzhy** [comment] 2024-09-03 07:37
i see the pull request will be automatically merged. Do you need to review it?

**Comment by patriksvensson** [comment] 2024-09-03 08:45
@sdwdjzhy You haven't created a pull request for this issue, so not sure what will be merged.

**Comment by patriksvensson** [comment] 2024-09-03 12:57
It looks like this has something to do with your terminal font, because [℃](https://www.compart.com/en/unicode/U+2103) and [℉](https://www.compart.com/en/unicode/U+2109) are not considered to be wide characters.  

Maybe `℃` and `℉` aren't available in your terminal font, and the terminal falls back to another font with a different width?

I've tested this using 6 terminals on 3 different OSes and cannot reproduce what you're seeing.

![image](https://github.com/user-attachments/assets/7ad46130-bfd4-4c74-8336-b71e205dbf08)

![image](https://github.com/user-attachments/assets/2c2d1fc4-21c5-4259-a7bb-972f28f84464)

![image](https://github.com/user-attachments/assets/7d8ca55e-bdd3-4d0b-ae37-3a3ef8c81f19)

**Closed** 2024-09-03 19:17 UTC
Labels: bug
